Navigation
Team-Surtes/Website pull request #3
Opened 2024-02-06 18:56 UTC by t0yamont

Header Layout: For the header layout I changed to a felx container with justify-between and text-center classes, making the items more eavenly distributed on the line with centered-align text.

Logo: I made the logo's height and horizontal margins dynamic, depending on if the drawer is open or not.

Navigation Links: I changed the navigation links from vertical to a horizontal layout and made them expand on the navigation bar without taking actual page space. Also added additional classes for transformation and hover effect.

2024-02-12 13:33 UTC, g30r93g commented on components/homepage/Hero.vue
requires conversion to tailwind

2024-02-12 13:34 UTC, g30r93g requested changes
Convert transition to tailwind. Use Google Gemini or ChatGPT for assistance

2024-02-12 14:03 UTC, t0yamont commented
CSS changed to Tailwind.

2024-02-14 22:09 UTC, g30r93g requested changes
Please rerun with `yarn` instead of `npm` and ensure new `yarn.lock` is generated

2024-02-15 15:19 UTC, t0yamont commented
Deleted the package-lock.json file and installed gsap dependencie through yarn

2024-02-21 14:49 UTC, closed without merging